export default {
  kind: 'case-study',
  order: 2,
  number: '02',
  company: 'Netflix',
  title: 'Console',
  subtitle: 'The Front Door for Software Ownership and Development',
  accent: 'purple',
  sections: [
    { id: 'discovery',       label: 'Problem Definition' },
    { id: 'research',        label: 'Research'           },
    { id: 'vision',          label: 'Vision Setting'     },
    { id: 'going-broad',     label: 'Going Broad'        },
    { id: 'narrowing-focus', label: 'Narrowing Focus'    },
    { id: 'solution',        label: 'Solution'           },
    { id: 'reception',       label: 'Reception'          },
  ],
  metadata: [
    { label: 'Role',     value: 'Product Designer'        },
    { label: 'Team',     value: 'Sole designer, end-to-end' },
    { label: 'Duration', value: '2021 – early 2023'       },
    { label: 'Industry', value: 'Streaming / DevTools'    },
    { label: 'Impact',   value: 'TBD'                     },
  ],
};
